export const KEY_STORAGE = {
    TOKEN: 'TOKEN',
    EMAIL: 'EMAIL',
    ORGANIZATION_ID: 'ORGANIZATION_ID',
    ADDRESS: 'ADDRESS',
    AUTHORIZATIONS: 'AUTHORIZATIONS',
    NAME: 'NAME',
    AVATAR_ID: 'AVATAR_ID',
    AVATAR: 'AVATAR'
};